/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adaa;

//import java.awt.*;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swingViewer.*;
import org.graphstream.ui.view.*;
import java.io.*;
import java.util.Scanner;
import org.graphstream.algorithm.Kruskal;
import org.graphstream.algorithm.Dijkstra;
//import org.graphstream.ui.view.ViewerPipe;


/**
 *
 * @author SionPark
 */
public class window extends javax.swing.JFrame {
    /**
     * Creates new form window
     */
    public window() {
        initComponents();
         System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
    }
    
    public static Graph graph = new DefaultGraph("practice");
    private static String css = "node {size:34px;" +
                           
                                "text-size: 20;"
                              + "fill-color: #eeedef;}" +
                             
                             "edge { " +
                                    "text-size: 20;" +
                                    "arrow-size: 7px;"+
                                    "fill-color: black; size: 2px;"
                                    +"text-offset: 3px;"
                                    + "text-alignment: center;}";
    
    private static String layout1 = "node {" +
                                    "shape: box;"+
                                    "arrow-shape: diamond;" +
                                    "fill-color: #e9d6fc;"+
                                    "shadow-color: #8d59af;}" +
                             
                                    "edge { " +
                                    "text-size: 20;" +
                                    "fill-color: #b772e5; size: 2px;"+                            
                                        "text-color: #8029d8;}";
                                    
    private static String layout2 = "node {" +
                                    "fill-color: #b5beff;"+
                                    "shadow-color: #527bbf;"+
                                    "shape: cross;"
                                    + " }" +                
                                    "edge { text-color: #2348af; " +
                                    "fill-color: #6a9ced; size: 2px;}";
    
     private static  String css2 = "edge .notintree {size:2px;} " +
                                    "edge .intree {size:5px;fill-color:red;}";

     public static boolean firstLayout = true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Minimum Spanning Tree");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Shortest Path");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("        ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText(" ");

        jLabel1.setText("Start Node:");

        jLabel2.setText("End Node:");

        jButton2.setText("Layout1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("layout2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose layout for graph");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        graph.addAttribute("ui.stylesheet", css2);
              
            
        Kruskal kruskal = new Kruskal("ui.class", "intree", "notintree");
        kruskal.init(graph);
        kruskal.compute();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       
        String startNode = jTextField1.getText();
        String endNode = jTextField2.getText();
        if (startNode == null || endNode == null){
            System.out.println("alert invalid node");
        }
        Dijkstra dijkstra = new Dijkstra(Dijkstra.Element.EDGE, "result", "weight");

        // Compute the shortest paths in g from A to all nodes
        dijkstra.init(graph);
        dijkstra.setSource(graph.getNode(startNode.trim()));
        graph.getNode(startNode.trim()).addAttribute("ui.style","fill-color: #54a863;" );
        dijkstra.compute();
       
        for (Node node : dijkstra.getPathNodes(graph.getNode(endNode.trim())))
             node.addAttribute("ui.style", "fill-color: #54a863;");

        // Color in red all the edges in the shortest path tree
        for (Edge edge : dijkstra.getPathEdges(graph.getNode(endNode.trim())))
            edge.addAttribute("ui.style", "fill-color: #71e886; size: 3px;");

         dijkstra.clear();
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Clean graph 
          graph.removeAttribute("ui.stylesheet");
          graph.addAttribute("ui.stylesheet", css);
          if (firstLayout){
              graph.addAttribute("ui.stylesheet", layout1);
          }
          else{
              graph.addAttribute("ui.stylesheet", layout2);
          }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // layout1
       // graph.removeAttribute("ui.stylesheet");
        firstLayout = true;
        graph.removeAttribute(css2);
        graph.addAttribute("ui.stylesheet", css);
        graph.addAttribute("ui.stylesheet", layout1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       // graph.removeAttribute("ui.stylesheet");
        firstLayout = false;
        graph.removeAttribute("ui.stylesheet");
        graph.addAttribute("ui.stylesheet", css);
        graph.addAttribute("ui.stylesheet", layout2);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      
       window myWindow = new window();
       //JPanel panel = new JPanel();
        try
        {
            //File fr =new File("./input.txt");
            Scanner input = new Scanner(new BufferedReader(new FileReader(args[0])));
                      // String css = "edge {size:1px;fill-color:gray;} " ;
                       
            graph.setStrict(false);
            int numNode = 0;
            String edge = "";
            while(input.hasNext())
            {
                String s = input.next();
                String node = s.substring(0,1);
                if (numNode == 2){
                    graph.addEdge(edge,edge.substring(0,1), edge.substring(1,2),true).addAttribute("weight",node);
                    graph.getEdge(edge).addAttribute("ui.label",node);
                    numNode=0;
                    edge = "";
                }
                else if(numNode < 2){
                    edge += node;               
                    graph.addNode(node);  
                    graph.getNode(node).addAttribute("ui.label",node);                                       
                    numNode ++;
                }
                
            }
           graph.addAttribute("ui.stylesheet",css); 
     
            Viewer viewer =new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
            viewer.enableAutoLayout();
            ViewPanel view =  viewer.addDefaultView(false);

            view.setSize(600,550);

            myWindow.jPanel1.add(view);

            myWindow.pack();
        }
        catch(ArrayIndexOutOfBoundsException ex)
        {
            System.out.println("\nPlease Enter the File Name in Command Line Argument. \n"+
            "For Example :- java MyFileReader C:\\Users\\Desktop\\File1.txt");
        }
        catch(IOException ex)
        {
                System.out.println("File Does Not Found in given Directory. ");
        }
               

        myWindow.setVisible(true);
	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
